spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jwt_demo_db2?useSSL=false
    username: root
    password: root_531999
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql

# email properties

  mail:

    host: smtp.gmail.com
    port: 587
    username: "abdullah7@std.mans.edu.eg"
    password: "qrob vpcx kjwr xsrs"
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          auth: true
          starttles:
            enable: true
            requird: true

#qrob vpcx kjwr xsrs
#  spring.mail.host=smtp.gmail.com
#  spring.mail.port=587
#  spring.mail.username=your-email@gmail.com
#  spring.mail.password=your-app-password
#  spring.mail.properties.mail.smtp.auth=true
#  spring.mail.properties.mail.smtp.starttls.enable=true
#  spring.mail.properties.mail.smtp.starttls.required=true
#  spring.mail.properties.mail.smtp.connectiontimeout=5000
#  spring.mail.properties.mail.smtp.timeout=5000
#  spring.mail.properties.mail.smtp.writetimeout=5000
